### ISSUE TITLE
Log Data errors better

### ISSUE THREAD

**Issue by yschimke** [joreilly/Confetti#275]
Some data errors in wear app.

Wear app shouldn't assert no errors, but reporting this anyway.

```
10:52:31.920  E  FATAL EXCEPTION: main
                 Process: dev.johnoreilly.confetti, PID: 11511
                 com.apollographql.apollo3.exception.ApolloException: The response has errors: [Error(message = Exception while fetching data (/sessions) : name must not be empty or null, locations = [Location(line = 1, column = 73)], path=[sessions], extensions = null, nonStandardFields = null), Error(message = Exception while fetching data (/speakers) : name must not be empty or null, locations = [Location(line = 1, column = 181)], path=[speakers], extensions = null, nonStandardFields = null), Error(message = Exception while fetching data (/rooms) : name must not be empty or null, locations = [Location(line = 1, column = 223)], path=[rooms], extensions = null, nonStandardFields = null), Error(message = Exception while fetching data (/config) : name must not be empty or null, locations = [Location(line = 1, column = 259)], path=[config], extensions = null, nonStandardFields = null)]
                 	at com.apollographql.apollo3.api.ApolloResponse.dataAssertNoErrors(ApolloResponse.kt:77)
                 	at dev.johnoreilly.confetti.wear.home.HomeViewModel$conferenceDataFlow$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:224)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
                 	at com.apollographql.apollo3.cache.normalized.FetchPolicyInterceptors$CacheFirstInterceptor$1$intercept$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:223)
                 	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7651)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ed6a03, Dispatchers.Main.immediate]
```

**Comment by martinbonnin** [comment]
Oopps that one's on me, I'll check in a few minutes. Do you know what query triggered this?

**Comment by yschimke** [comment]
GetConferenceDataQuery?

**Comment by martinbonnin** [comment]
Looks like it crashes [here](https://github.com/joreilly/Confetti/blob/1cfc16b93e151afd9a6b0ae16d75e766f5bcc905/backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt#L192), can you double check your "conference" header?

**Comment by yschimke** [comment]
Yep, that's it.  Sorry.

"conference:"

**Comment by martinbonnin** [comment]
No worries, the error should be more explicit, let's keep this ticket open as a reminder to log better error messages.
